# settings!

[credentials]
bot_token = 'TOKEN'
db_name = ''
db_uname = ''
db_pass = ''

[owner]
owner_id = ''

[settings]
chat_id_bind = [
    ]
chat_id_ban = [
]
welcome_message = 'hello! i am bot!'
