# settings!
fenrir_version = '1.05'
db_version = '1.00'

[credentials]
bot_token = 'TOKEN'
db_name = ''
db_uname = ''
db_pass = ''

[owner]
owner_id = ''

[settings]
chat_id_mode = 'ban'    #'ban' or 'bind'
chat_id_bind = [
    ]
chat_id_ban = [
]
welcome_message = 'hello! i am bot!'